Repository netgrif/petriflow.js, pull requests merged in 2021-12, with the labels that each got.

#15 [PF-14] Data validation getter/setter
  src/lib/export/export.service.ts
  src/lib/import/import.service.ts
  src/lib/model/data-variable/data-variable.ts
  src/test/petriflow.spec.js
Labels: Bugfix, Small

#14 [PF-13] Clean up petriflow schema
  package-lock.json
  src/lib/export/export-utils.ts
  src/lib/export/export.service.ts
  src/lib/import/import-utils.ts
  src/lib/import/import.service.ts
  src/lib/model/transition/logic.ts
  src/test/petriflow.spec.js
  src/test/resources/petriflow_test.xml
Labels: Documentation, Improvement, Breaking change, Small

#12 [PF-11] Update TS library
  package-lock.json
  src/lib/export/export-utils.ts
  src/lib/export/export.service.ts
  src/lib/import/import-utils.ts
  src/lib/import/import.service.ts
  src/lib/model/index.ts
  src/lib/model/petri-net.ts
  src/lib/model/petrinet/function-scope.enum.ts
  src/lib/model/petrinet/petriflow-function.ts
  src/test/petriflow.spec.js
  src/test/resources/petriflow_test.xml
Labels: Documentation, New feature, Medium

#16 [PF-16] Anonymous role
  src/lib/export/export.service.ts
  src/lib/import/import.service.ts
  src/lib/model/petri-net.ts
  src/test/petriflow.spec.js
  src/test/resources/petriflow_test.xml
Labels: New feature, Breaking change, Extra Small

#18 [PF-17] - Layout imports rows cols with default value 0
  src/lib/export/export.service.ts
  src/lib/import/import-utils.ts
  src/lib/import/import.service.ts
Labels: Extra Small

#19 [PF-18] - Validation does not clone properties
  src/lib/model/data-variable/validation.ts
Labels: Extra Small

#20 [PF-19] - Export tag should escape XML invalid characters
  src/lib/export/export-utils.ts
Labels: Extra Small
