Repository netgrif/petriflow.js, pull requests merged in 2022-03, with the labels that each got.

#33 Release 1.3.3
  .github/workflows/release-build.yml
  CONTRIBUTING.md
  README.md
  package-lock.json
  src/lib/export/export-utils.ts
  src/lib/export/export.service.ts
  src/lib/import/import-utils.ts
  src/lib/import/import.service.ts
  src/lib/model/index.ts
  src/lib/model/petri-net.ts
  src/lib/model/petrinet/event-source.ts
  src/lib/model/role/role.ts
  src/lib/model/transition/compact-direction.enum.ts
  src/lib/model/transition/datagroup.ts
  src/lib/model/transition/hide-empty-rows.enum.ts
  src/lib/model/transition/transition-layout.ts
  src/test/petriflow.spec.js
  src/test/resources/petriflow_test.xml
Labels: Bugfix, Documentation, Improvement, Large, Critical, Release

#28 [PF-26] - Readme update
  CONTRIBUTING.md
  README.md
Labels: Extra Small

#31 [PF-31] - Invalid XML characters
  package-lock.json
  src/lib/export/export-utils.ts
  src/lib/import/import-utils.ts
  src/lib/model/petrinet/event-source.ts
  src/test/petriflow.spec.js
  src/test/resources/petriflow_test.xml
Labels: Extra Small

#32 [PF-32] - Predefined role ref
  src/lib/import/import-utils.ts
  src/lib/model/petri-net.ts
  src/lib/model/role/role.ts
  src/test/petriflow.spec.js
  src/test/resources/petriflow_test.xml
Labels: Small
